language: python
python:
  - "2.7"
services:
  - mysql
install: "pip install -r requirements.txt"
before_script:
  - mysql -e 'create database ckl_challenge;'
  - python manage.py syncdb --noinput
script:
  - python manage.py test
