version: '2'
services:
    mysql:
        image: mysql
        volumes:
            - ./database/data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: "root"
            MYSQL_DATABASE: "ckl_challenge"
        ports:
            - "3306:3306"
    application:
        tty: true
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        environment:
            ENV: "development"
        ports:
            - "8000:8000"
        links:
            - mysql
        volumes:
            - .:/var/www