# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
