# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20161101_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
