# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20161101_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
